### ISSUE TITLE
其他的都类似

### ISSUE THREAD

**Issue by milk531** [AtlasXV/Eval-Indexnet#2]
https://github.com/AtlasXV/Eval-Indexnet/blob/ee47c985fb1c5cbcd1f958ab5633e839f10338a3/evaluator.py#L52
compute_mse_loss
compute_gradient_loss
compute_connectivity_loss

这些也是同理，如果不需要trimap参与评估，mask都设为1

**Comment by eroscai** [comment]
嗯，已经都同步修改完毕
